//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



public partial class SiteEntitiesDataContext : Microsoft.SharePoint.Linq.DataContext {
	
	#region Extensibility Method Definitions
	partial void OnCreated();
	#endregion
	
	public SiteEntitiesDataContext(string requestUrl) : 
			base(requestUrl) {
		this.OnCreated();
	}
	
	/// <summary>
	/// CustomTasks
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="CustomTasks")]
	public Microsoft.SharePoint.Linq.EntityList<Элемент> CustomTasks {
		get {
			return this.GetList<Элемент>("CustomTasks");
		}
	}
	
	/// <summary>
	/// Library for developer documents
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Dev Library")]
	public Microsoft.SharePoint.Linq.EntityList<Документ> DevLibrary {
		get {
			return this.GetList<Документ>("Dev Library");
		}
	}
	
	/// <summary>
	/// Library for hr documents
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="HR Library")]
	public Microsoft.SharePoint.Linq.EntityList<Документ> HRLibrary {
		get {
			return this.GetList<Документ>("HR Library");
		}
	}
	
	/// <summary>
	/// Library for QA documents
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="QA Library")]
	public Microsoft.SharePoint.Linq.EntityList<Документ> QALibrary {
		get {
			return this.GetList<Документ>("QA Library");
		}
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="tt")]
	public Microsoft.SharePoint.Linq.EntityList<Элемент> Tt {
		get {
			return this.GetList<Элемент>("tt");
		}
	}
	
	/// <summary>
	/// This list hosts the Workflow
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Workflow Host List")]
	public Microsoft.SharePoint.Linq.EntityList<Элемент> WorkflowHostList {
		get {
			return this.GetList<Элемент>("Workflow Host List");
		}
	}
	
	/// <summary>
	/// Tasks of Workflow
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Workflow Tasks")]
	public Microsoft.SharePoint.Linq.EntityList<Элемент> WorkflowTasks {
		get {
			return this.GetList<Элемент>("Workflow Tasks");
		}
	}
	
	/// <summary>
	/// Библиотека стилей служит для хранения таблиц стилей, например файлов CSS или XSL. Таблицы стилей в этой коллекции доступны для данного сайта и его дочерних сайтов.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Библиотека стилей")]
	public Microsoft.SharePoint.Linq.EntityList<Документ> БиблиотекаСтилей {
		get {
			return this.GetList<Документ>("Библиотека стилей");
		}
	}
	
	/// <summary>
	/// В списке "Задачи" ведется перечень работ, которые предстоит выполнить вам или вашей рабочей группе.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Задачи")]
	public Microsoft.SharePoint.Linq.EntityList<Элемент> Задачи {
		get {
			return this.GetList<Элемент>("Задачи");
		}
	}
	
	/// <summary>
	/// Этот список служит для отслеживания предстоящих событий, обновления состояния и других новостей группы.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Извещения")]
	public Microsoft.SharePoint.Linq.EntityList<Извещение> Извещения {
		get {
			return this.GetList<Извещение>("Извещения");
		}
	}
	
	/// <summary>
	/// Список "Календарь" служит для информирования о предстоящих собраниях, приближающихся сроках и других важных событиях.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Календарь")]
	public Microsoft.SharePoint.Linq.EntityList<КалендарьСобытие> Календарь {
		get {
			return this.GetList<КалендарьСобытие>("Календарь");
		}
	}
	
	/// <summary>
	/// Список "Коллективное обсуждение" используется для проведения обсуждений в стиле группы новостей на темы, актуальные для данной рабочей группы.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Коллективное обсуждение")]
	public Microsoft.SharePoint.Linq.EntityList<Элемент> КоллективноеОбсуждение {
		get {
			return this.GetList<Элемент>("Коллективное обсуждение");
		}
	}
	
	/// <summary>
	/// Эта библиотека служит для хранения файлов, которые находятся на страницах этого сайта, таких как изображения на вики-страницах.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Материалы сайта")]
	public Microsoft.SharePoint.Linq.EntityList<Документ> МатериалыСайта {
		get {
			return this.GetList<Документ>("Материалы сайта");
		}
	}
	
	/// <summary>
	/// Добавьте документ в эту библиотеку, чтобы обеспечить возможность совместной работы с ним для членов группы.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Общие документы")]
	public Microsoft.SharePoint.Linq.EntityList<Документ> ОбщиеДокументы {
		get {
			return this.GetList<Документ>("Общие документы");
		}
	}
	
	/// <summary>
	/// Список ссылок предназначен для хранения ссылок на веб-страницы, которые могут быть интересны или полезны членам вашей группы.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Ссылки")]
	public Microsoft.SharePoint.Linq.EntityList<Ссылка> Ссылки {
		get {
			return this.GetList<Ссылка>("Ссылки");
		}
	}
	
	/// <summary>
	/// Эта библиотека служит для создания и хранения страниц на этом сайте.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Страницы сайта")]
	public Microsoft.SharePoint.Linq.EntityList<ВикиСтраница> СтраницыСайта {
		get {
			return this.GetList<ВикиСтраница>("Страницы сайта");
		}
	}
}

/// <summary>
/// Создание элемента списка.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Элемент", Id="0x01")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Задача))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Документ))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Папка))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Извещение))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Событие))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Сообщение))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Ссылка))]
public partial class Элемент : Microsoft.SharePoint.Linq.ITrackEntityState, Microsoft.SharePoint.Linq.ITrackOriginalValues, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
	
	private System.Nullable<int> _id;
	
	private System.Nullable<int> _version;
	
	private string _path;
	
	private Microsoft.SharePoint.Linq.EntityState _entityState;
	
	private System.Collections.Generic.IDictionary<string, object> _originalValues;
	
	protected string _название;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion

	Microsoft.SharePoint.Linq.EntityState Microsoft.SharePoint.Linq.ITrackEntityState.EntityState {
		get {
			return this._entityState;
		}
		set {
			if ((value != this._entityState)) {
				this._entityState = value;
			}
		}
	}

	System.Collections.Generic.IDictionary<string, object> Microsoft.SharePoint.Linq.ITrackOriginalValues.OriginalValues {
		get {
			if ((null == this._originalValues)) {
				this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
			}
			return this._originalValues;
		}
	}
	
	public Элемент() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ID", Storage="_id", ReadOnly=true, FieldType="Counter")]
	public System.Nullable<int> Id {
		get {
			return this._id;
		}
		set {
			if ((value != this._id)) {
				this.OnPropertyChanging("Id", this._id);
				this._id = value;
				this.OnPropertyChanged("Id");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="owshiddenversion", Storage="_version", ReadOnly=true, FieldType="Integer")]
	public System.Nullable<int> Version {
		get {
			return this._version;
		}
		set {
			if ((value != this._version)) {
				this.OnPropertyChanging("Version", this._version);
				this._version = value;
				this.OnPropertyChanged("Version");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileDirRef", Storage="_path", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
	public string Path {
		get {
			return this._path;
		}
		set {
			if ((value != this._path)) {
				this.OnPropertyChanging("Path", this._path);
				this._path = value;
				this.OnPropertyChanged("Path");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Title", Storage="_название", Required=true, FieldType="Text")]
	public virtual string Название {
		get {
			return this._название;
		}
		set {
			if ((value != this._название)) {
				this.OnPropertyChanging("Название", this._название);
				this._название = value;
				this.OnPropertyChanged("Название");
			}
		}
	}
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	protected virtual void OnPropertyChanged(string propertyName) {
		if ((null != this.PropertyChanged)) {
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	protected virtual void OnPropertyChanging(string propertyName, object value) {
		if ((null == this._originalValues)) {
			this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
		}
		if ((false == this._originalValues.ContainsKey(propertyName))) {
			this._originalValues.Add(propertyName, value);
		}
		if ((null != this.PropertyChanging)) {
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
}

/// <summary>
/// Отслеживание поручения, которое должен выполнить пользователь или рабочая группа.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Задача", Id="0x0108")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(TtЗадача))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(ЗадачиЗадача))]
public partial class Задача : Элемент {
	
	private System.Nullable<double> _завершения;
	
	private string _основнойТекст;
	
	private System.Nullable<System.DateTime> _датаНачала;
	
	protected System.Nullable<System.DateTime> _срок;
	
	private System.Nullable<Важность> _важность;
	
	protected System.Nullable<СостояниеЗадачи> _состояниеЗадачи;
	
	private System.Nullable<int> _комуНазначеноId;
	
	private string _комуНазначено;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Задача() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PercentComplete", Storage="_завершения", FieldType="Number")]
	public System.Nullable<double> Завершения {
		get {
			return this._завершения;
		}
		set {
			if ((value != this._завершения)) {
				this.OnPropertyChanging("Завершения", this._завершения);
				this._завершения = value;
				this.OnPropertyChanged("Завершения");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Body", Storage="_основнойТекст", FieldType="Note")]
	public string ОсновнойТекст {
		get {
			return this._основнойТекст;
		}
		set {
			if ((value != this._основнойТекст)) {
				this.OnPropertyChanging("ОсновнойТекст", this._основнойТекст);
				this._основнойТекст = value;
				this.OnPropertyChanged("ОсновнойТекст");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="StartDate", Storage="_датаНачала", FieldType="DateTime")]
	public System.Nullable<System.DateTime> ДатаНачала {
		get {
			return this._датаНачала;
		}
		set {
			if ((value != this._датаНачала)) {
				this.OnPropertyChanging("ДатаНачала", this._датаНачала);
				this._датаНачала = value;
				this.OnPropertyChanged("ДатаНачала");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="TaskDueDate", Storage="_срок", FieldType="DateTime")]
	public virtual System.Nullable<System.DateTime> Срок {
		get {
			return this._срок;
		}
		set {
			if ((value != this._срок)) {
				this.OnPropertyChanging("Срок", this._срок);
				this._срок = value;
				this.OnPropertyChanged("Срок");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Priority", Storage="_важность", FieldType="Choice")]
	public System.Nullable<Важность> Важность {
		get {
			return this._важность;
		}
		set {
			if ((value != this._важность)) {
				this.OnPropertyChanging("Важность", this._важность);
				this._важность = value;
				this.OnPropertyChanged("Важность");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="TaskStatus", Storage="_состояниеЗадачи", FieldType="Choice")]
	public virtual System.Nullable<СостояниеЗадачи> СостояниеЗадачи {
		get {
			return this._состояниеЗадачи;
		}
		set {
			if ((value != this._состояниеЗадачи)) {
				this.OnPropertyChanging("СостояниеЗадачи", this._состояниеЗадачи);
				this._состояниеЗадачи = value;
				this.OnPropertyChanged("СостояниеЗадачи");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AssignedTo", Storage="_комуНазначеноId", FieldType="User", IsLookupId=true)]
	public System.Nullable<int> КомуНазначеноId {
		get {
			return this._комуНазначеноId;
		}
		set {
			if ((value != this._комуНазначеноId)) {
				this.OnPropertyChanging("КомуНазначеноId", this._комуНазначеноId);
				this._комуНазначеноId = value;
				this.OnPropertyChanged("КомуНазначеноId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AssignedTo", Storage="_комуНазначено", ReadOnly=true, FieldType="User", IsLookupValue=true)]
	public string КомуНазначено {
		get {
			return this._комуНазначено;
		}
		set {
			if ((value != this._комуНазначено)) {
				this.OnPropertyChanging("КомуНазначено", this._комуНазначено);
				this._комуНазначено = value;
				this.OnPropertyChanged("КомуНазначено");
			}
		}
	}
}

/// <summary>
/// Создание документа.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Документ", Id="0x0101")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(ВикиСтраница))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Форма))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Рисунок))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(HRLibraryДокумент))]
public partial class Документ : Элемент {
	
	private string _имя;
	
	private string _авторИзмененийВДокументе;
	
	private string _создательДокумента;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Документ() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileLeafRef", Storage="_имя", Required=true, FieldType="File")]
	public string Имя {
		get {
			return this._имя;
		}
		set {
			if ((value != this._имя)) {
				this.OnPropertyChanging("Имя", this._имя);
				this._имя = value;
				this.OnPropertyChanged("Имя");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Modified_x0020_By", Storage="_авторИзмененийВДокументе", ReadOnly=true, FieldType="Text")]
	public string АвторИзмененийВДокументе {
		get {
			return this._авторИзмененийВДокументе;
		}
		set {
			if ((value != this._авторИзмененийВДокументе)) {
				this.OnPropertyChanging("АвторИзмененийВДокументе", this._авторИзмененийВДокументе);
				this._авторИзмененийВДокументе = value;
				this.OnPropertyChanged("АвторИзмененийВДокументе");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Created_x0020_By", Storage="_создательДокумента", ReadOnly=true, FieldType="Text")]
	public string СоздательДокумента {
		get {
			return this._создательДокумента;
		}
		set {
			if ((value != this._создательДокумента)) {
				this.OnPropertyChanging("СоздательДокумента", this._создательДокумента);
				this._создательДокумента = value;
				this.OnPropertyChanged("СоздательДокумента");
			}
		}
	}
}

/// <summary>
/// Создание папки.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Папка", Id="0x0120")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(СуммарнаяЗадача))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Обсуждение))]
public partial class Папка : Элемент {
	
	private string _имя;
	
	private System.Nullable<int> _числоДочернихЭлементовId;
	
	private string _числоДочернихЭлементовItemChildCount;
	
	private System.Nullable<int> _числоДочернихПапокId;
	
	private string _числоДочернихПапокFolderChildCount;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Папка() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileLeafRef", Storage="_имя", Required=true, FieldType="File")]
	public virtual string Имя {
		get {
			return this._имя;
		}
		set {
			if ((value != this._имя)) {
				this.OnPropertyChanging("Имя", this._имя);
				this._имя = value;
				this.OnPropertyChanged("Имя");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Название {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Папка.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Папка.");
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ItemChildCount", Storage="_числоДочернихЭлементовId", ReadOnly=true, FieldType="Lookup", IsLookupId=true)]
	public System.Nullable<int> ЧислоДочернихЭлементовId {
		get {
			return this._числоДочернихЭлементовId;
		}
		set {
			if ((value != this._числоДочернихЭлементовId)) {
				this.OnPropertyChanging("ЧислоДочернихЭлементовId", this._числоДочернихЭлементовId);
				this._числоДочернихЭлементовId = value;
				this.OnPropertyChanged("ЧислоДочернихЭлементовId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ItemChildCount", Storage="_числоДочернихЭлементовItemChildCount", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
	public string ЧислоДочернихЭлементовItemChildCount {
		get {
			return this._числоДочернихЭлементовItemChildCount;
		}
		set {
			if ((value != this._числоДочернихЭлементовItemChildCount)) {
				this.OnPropertyChanging("ЧислоДочернихЭлементовItemChildCount", this._числоДочернихЭлементовItemChildCount);
				this._числоДочернихЭлементовItemChildCount = value;
				this.OnPropertyChanged("ЧислоДочернихЭлементовItemChildCount");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FolderChildCount", Storage="_числоДочернихПапокId", ReadOnly=true, FieldType="Lookup", IsLookupId=true)]
	public System.Nullable<int> ЧислоДочернихПапокId {
		get {
			return this._числоДочернихПапокId;
		}
		set {
			if ((value != this._числоДочернихПапокId)) {
				this.OnPropertyChanging("ЧислоДочернихПапокId", this._числоДочернихПапокId);
				this._числоДочернихПапокId = value;
				this.OnPropertyChanged("ЧислоДочернихПапокId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FolderChildCount", Storage="_числоДочернихПапокFolderChildCount", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
	public string ЧислоДочернихПапокFolderChildCount {
		get {
			return this._числоДочернихПапокFolderChildCount;
		}
		set {
			if ((value != this._числоДочернихПапокFolderChildCount)) {
				this.OnPropertyChanging("ЧислоДочернихПапокFolderChildCount", this._числоДочернихПапокFolderChildCount);
				this._числоДочернихПапокFolderChildCount = value;
				this.OnPropertyChanged("ЧислоДочернихПапокFolderChildCount");
			}
		}
	}
}

/// <summary>
/// Создание элемента новостей, сведений о состоянии или другого небольшого информационного объекта.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Извещение", Id="0x0104")]
public partial class Извещение : Элемент {
	
	private string _основнойТекст;
	
	private System.Nullable<System.DateTime> _срокДействия;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Извещение() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Body", Storage="_основнойТекст", FieldType="Note")]
	public string ОсновнойТекст {
		get {
			return this._основнойТекст;
		}
		set {
			if ((value != this._основнойТекст)) {
				this.OnPropertyChanging("ОсновнойТекст", this._основнойТекст);
				this._основнойТекст = value;
				this.OnPropertyChanged("ОсновнойТекст");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Expires", Storage="_срокДействия", FieldType="DateTime")]
	public System.Nullable<System.DateTime> СрокДействия {
		get {
			return this._срокДействия;
		}
		set {
			if ((value != this._срокДействия)) {
				this.OnPropertyChanging("СрокДействия", this._срокДействия);
				this._срокДействия = value;
				this.OnPropertyChanged("СрокДействия");
			}
		}
	}
}

/// <summary>
/// Создание собрания, крайнего срока или другого события.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Событие", Id="0x0102")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(КалендарьСобытие))]
public partial class Событие : Элемент {
	
	private string _расположение;
	
	protected System.Nullable<System.DateTime> _времяНачала;
	
	private System.Nullable<System.DateTime> _времяОкончания;
	
	protected string _описание;
	
	private System.Nullable<bool> _целыйДень;
	
	private System.Nullable<bool> _повторение;
	
	private System.Nullable<bool> _рабочаяОбласть;
	
	private System.Nullable<Категория> _категория;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Событие() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Location", Storage="_расположение", FieldType="Text")]
	public string Расположение {
		get {
			return this._расположение;
		}
		set {
			if ((value != this._расположение)) {
				this.OnPropertyChanging("Расположение", this._расположение);
				this._расположение = value;
				this.OnPropertyChanged("Расположение");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="StartDate", Storage="_времяНачала", Required=true, FieldType="DateTime")]
	public virtual System.Nullable<System.DateTime> ВремяНачала {
		get {
			return this._времяНачала;
		}
		set {
			if ((value != this._времяНачала)) {
				this.OnPropertyChanging("ВремяНачала", this._времяНачала);
				this._времяНачала = value;
				this.OnPropertyChanged("ВремяНачала");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EndDate", Storage="_времяОкончания", Required=true, FieldType="DateTime")]
	public System.Nullable<System.DateTime> ВремяОкончания {
		get {
			return this._времяОкончания;
		}
		set {
			if ((value != this._времяОкончания)) {
				this.OnPropertyChanging("ВремяОкончания", this._времяОкончания);
				this._времяОкончания = value;
				this.OnPropertyChanged("ВремяОкончания");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Comments", Storage="_описание", FieldType="Note")]
	public virtual string Описание {
		get {
			return this._описание;
		}
		set {
			if ((value != this._описание)) {
				this.OnPropertyChanging("Описание", this._описание);
				this._описание = value;
				this.OnPropertyChanged("Описание");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="fAllDayEvent", Storage="_целыйДень", FieldType="AllDayEvent")]
	public System.Nullable<bool> ЦелыйДень {
		get {
			return this._целыйДень;
		}
		set {
			if ((value != this._целыйДень)) {
				this.OnPropertyChanging("ЦелыйДень", this._целыйДень);
				this._целыйДень = value;
				this.OnPropertyChanged("ЦелыйДень");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="fRecurrence", Storage="_повторение", FieldType="Recurrence")]
	public System.Nullable<bool> Повторение {
		get {
			return this._повторение;
		}
		set {
			if ((value != this._повторение)) {
				this.OnPropertyChanging("Повторение", this._повторение);
				this._повторение = value;
				this.OnPropertyChanged("Повторение");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WorkspaceLink", Storage="_рабочаяОбласть", FieldType="CrossProjectLink")]
	public System.Nullable<bool> РабочаяОбласть {
		get {
			return this._рабочаяОбласть;
		}
		set {
			if ((value != this._рабочаяОбласть)) {
				this.OnPropertyChanging("РабочаяОбласть", this._рабочаяОбласть);
				this._рабочаяОбласть = value;
				this.OnPropertyChanged("РабочаяОбласть");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Category", Storage="_категория", FieldType="Choice")]
	public System.Nullable<Категория> Категория {
		get {
			return this._категория;
		}
		set {
			if ((value != this._категория)) {
				this.OnPropertyChanging("Категория", this._категория);
				this._категория = value;
				this.OnPropertyChanged("Категория");
			}
		}
	}
}

/// <summary>
/// Создание сообщения.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Сообщение", Id="0x0107")]
public partial class Сообщение : Элемент {
	
	private string _темаОбсуждения;
	
	private string _версия;
	
	private string _основнойТекст;
	
	private string _ответ;
	
	private string _запись;
	
	private string _цепочкиОбсуждения;
	
	private string _кемРазмещено;
	
	private string _отправительСообщения;
	
	private System.Nullable<int> _кемИзмененоId;
	
	private string _кемИзмененоNameWithPicture;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Сообщение() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DiscussionTitle", Storage="_темаОбсуждения", ReadOnly=true, FieldType="Computed")]
	public string ТемаОбсуждения {
		get {
			return this._темаОбсуждения;
		}
		set {
			if ((value != this._темаОбсуждения)) {
				this.OnPropertyChanging("ТемаОбсуждения", this._темаОбсуждения);
				this._темаОбсуждения = value;
				this.OnPropertyChanged("ТемаОбсуждения");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_UIVersionString", Storage="_версия", ReadOnly=true, FieldType="Text")]
	public string Версия {
		get {
			return this._версия;
		}
		set {
			if ((value != this._версия)) {
				this.OnPropertyChanging("Версия", this._версия);
				this._версия = value;
				this.OnPropertyChanged("Версия");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Body", Storage="_основнойТекст", FieldType="Note")]
	public string ОсновнойТекст {
		get {
			return this._основнойТекст;
		}
		set {
			if ((value != this._основнойТекст)) {
				this.OnPropertyChanging("ОсновнойТекст", this._основнойТекст);
				this._основнойТекст = value;
				this.OnPropertyChanged("ОсновнойТекст");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ReplyNoGif", Storage="_ответ", ReadOnly=true, FieldType="Computed")]
	public string Ответ {
		get {
			return this._ответ;
		}
		set {
			if ((value != this._ответ)) {
				this.OnPropertyChanging("Ответ", this._ответ);
				this._ответ = value;
				this.OnPropertyChanged("Ответ");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="BodyAndMore", Storage="_запись", ReadOnly=true, FieldType="Computed")]
	public string Запись {
		get {
			return this._запись;
		}
		set {
			if ((value != this._запись)) {
				this.OnPropertyChanging("Запись", this._запись);
				this._запись = value;
				this.OnPropertyChanged("Запись");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Threading", Storage="_цепочкиОбсуждения", ReadOnly=true, FieldType="Computed")]
	public string ЦепочкиОбсуждения {
		get {
			return this._цепочкиОбсуждения;
		}
		set {
			if ((value != this._цепочкиОбсуждения)) {
				this.OnPropertyChanging("ЦепочкиОбсуждения", this._цепочкиОбсуждения);
				this._цепочкиОбсуждения = value;
				this.OnPropertyChanged("ЦепочкиОбсуждения");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PersonViewMinimal", Storage="_кемРазмещено", ReadOnly=true, FieldType="Computed")]
	public string КемРазмещено {
		get {
			return this._кемРазмещено;
		}
		set {
			if ((value != this._кемРазмещено)) {
				this.OnPropertyChanging("КемРазмещено", this._кемРазмещено);
				this._кемРазмещено = value;
				this.OnPropertyChanged("КемРазмещено");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EmailSender", Storage="_отправительСообщения", FieldType="Note")]
	public string ОтправительСообщения {
		get {
			return this._отправительСообщения;
		}
		set {
			if ((value != this._отправительСообщения)) {
				this.OnPropertyChanging("ОтправительСообщения", this._отправительСообщения);
				this._отправительСообщения = value;
				this.OnPropertyChanged("ОтправительСообщения");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Название {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Сообщение.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Сообщение.");
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MyEditor", Storage="_кемИзмененоId", ReadOnly=true, FieldType="User", IsLookupId=true)]
	public System.Nullable<int> КемИзмененоId {
		get {
			return this._кемИзмененоId;
		}
		set {
			if ((value != this._кемИзмененоId)) {
				this.OnPropertyChanging("КемИзмененоId", this._кемИзмененоId);
				this._кемИзмененоId = value;
				this.OnPropertyChanged("КемИзмененоId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MyEditor", Storage="_кемИзмененоNameWithPicture", ReadOnly=true, FieldType="User", IsLookupValue=true)]
	public string КемИзмененоNameWithPicture {
		get {
			return this._кемИзмененоNameWithPicture;
		}
		set {
			if ((value != this._кемИзмененоNameWithPicture)) {
				this.OnPropertyChanging("КемИзмененоNameWithPicture", this._кемИзмененоNameWithPicture);
				this._кемИзмененоNameWithPicture = value;
				this.OnPropertyChanged("КемИзмененоNameWithPicture");
			}
		}
	}
}

/// <summary>
/// Создание ссылки на веб-страницу или другой ресурс.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Ссылка", Id="0x0105")]
public partial class Ссылка : Элемент {
	
	private string _uRLАдрес;
	
	private string _заметки;
	
	private string _uRLАдрес0;
	
	private string _uRLАдрес1;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Ссылка() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="URL", Storage="_uRLАдрес", Required=true, FieldType="Url")]
	public string URLАдрес {
		get {
			return this._uRLАдрес;
		}
		set {
			if ((value != this._uRLАдрес)) {
				this.OnPropertyChanging("URLАдрес", this._uRLАдрес);
				this._uRLАдрес = value;
				this.OnPropertyChanged("URLАдрес");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Comments", Storage="_заметки", FieldType="Note")]
	public string Заметки {
		get {
			return this._заметки;
		}
		set {
			if ((value != this._заметки)) {
				this.OnPropertyChanging("Заметки", this._заметки);
				this._заметки = value;
				this.OnPropertyChanged("Заметки");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="URLwMenu", Storage="_uRLАдрес0", ReadOnly=true, FieldType="Computed")]
	public string URLАдрес0 {
		get {
			return this._uRLАдрес0;
		}
		set {
			if ((value != this._uRLАдрес0)) {
				this.OnPropertyChanging("URLАдрес0", this._uRLАдрес0);
				this._uRLАдрес0 = value;
				this.OnPropertyChanged("URLАдрес0");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="URLNoMenu", Storage="_uRLАдрес1", ReadOnly=true, FieldType="Computed")]
	public string URLАдрес1 {
		get {
			return this._uRLАдрес1;
		}
		set {
			if ((value != this._uRLАдрес1)) {
				this.OnPropertyChanging("URLАдрес1", this._uRLАдрес1);
				this._uRLАдрес1 = value;
				this.OnPropertyChanged("URLАдрес1");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Название {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Ссылка.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Ссылка.");
		}
	}
}

/// <summary>
/// Создание вики-страницы.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Вики-страница", Id="0x010108")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(DevLibraryВикиСтраница))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(HRLibraryВикиСтраница))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(QALibraryВикиСтраница))]
public partial class ВикиСтраница : Документ {
	
	private string _викиКонтент;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public ВикиСтраница() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WikiField", Storage="_викиКонтент", FieldType="Note")]
	public virtual string ВикиКонтент {
		get {
			return this._викиКонтент;
		}
		set {
			if ((value != this._викиКонтент)) {
				this.OnPropertyChanging("ВикиКонтент", this._викиКонтент);
				this._викиКонтент = value;
				this.OnPropertyChanged("ВикиКонтент");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Название {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Вики-страница.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Вики-страница.");
		}
	}
}

/// <summary>
/// Заполнение формы.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Форма", Id="0x010101")]
public partial class Форма : Документ {
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Форма() {
		this.OnCreated();
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Название {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Форма.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Форма.");
		}
	}
}

/// <summary>
/// Отправка изображения или фотографии.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Рисунок", Id="0x010102")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(DevLibraryРисунок))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(QALibraryРисунок))]
public partial class Рисунок : Документ {
	
	private string _образец;
	
	private string _типФайла;
	
	private string _размерРисунка;
	
	private System.Nullable<int> _ширинаРисунка;
	
	private System.Nullable<int> _высотаРисунка;
	
	private System.Nullable<System.DateTime> _датаСозданияРисунка;
	
	private string _заметки;
	
	private string _флажокВыбора;
	
	private string _имя0;
	
	private string _обязательноеПоле;
	
	private string _ключевыеСлова;
	
	private string _эскиз;
	
	private string _вебПросмотр;
	
	private string _uRLАдресИзображенияДляПросмотра;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Рисунок() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PreviewOnForm", Storage="_образец", FieldType="Computed")]
	public virtual string Образец {
		get {
			return this._образец;
		}
		set {
			if ((value != this._образец)) {
				this.OnPropertyChanging("Образец", this._образец);
				this._образец = value;
				this.OnPropertyChanged("Образец");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileType", Storage="_типФайла", FieldType="Computed")]
	public virtual string ТипФайла {
		get {
			return this._типФайла;
		}
		set {
			if ((value != this._типФайла)) {
				this.OnPropertyChanging("ТипФайла", this._типФайла);
				this._типФайла = value;
				this.OnPropertyChanged("ТипФайла");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ImageSize", Storage="_размерРисунка", FieldType="Computed")]
	public virtual string РазмерРисунка {
		get {
			return this._размерРисунка;
		}
		set {
			if ((value != this._размерРисунка)) {
				this.OnPropertyChanging("РазмерРисунка", this._размерРисунка);
				this._размерРисунка = value;
				this.OnPropertyChanged("РазмерРисунка");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ImageWidth", Storage="_ширинаРисунка", ReadOnly=true, FieldType="Integer")]
	public virtual System.Nullable<int> ШиринаРисунка {
		get {
			return this._ширинаРисунка;
		}
		set {
			if ((value != this._ширинаРисунка)) {
				this.OnPropertyChanging("ШиринаРисунка", this._ширинаРисунка);
				this._ширинаРисунка = value;
				this.OnPropertyChanged("ШиринаРисунка");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ImageHeight", Storage="_высотаРисунка", ReadOnly=true, FieldType="Integer")]
	public virtual System.Nullable<int> ВысотаРисунка {
		get {
			return this._высотаРисунка;
		}
		set {
			if ((value != this._высотаРисунка)) {
				this.OnPropertyChanging("ВысотаРисунка", this._высотаРисунка);
				this._высотаРисунка = value;
				this.OnPropertyChanged("ВысотаРисунка");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ImageCreateDate", Storage="_датаСозданияРисунка", FieldType="DateTime")]
	public virtual System.Nullable<System.DateTime> ДатаСозданияРисунка {
		get {
			return this._датаСозданияРисунка;
		}
		set {
			if ((value != this._датаСозданияРисунка)) {
				this.OnPropertyChanging("ДатаСозданияРисунка", this._датаСозданияРисунка);
				this._датаСозданияРисунка = value;
				this.OnPropertyChanged("ДатаСозданияРисунка");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Comments", Storage="_заметки", FieldType="Note")]
	public virtual string Заметки {
		get {
			return this._заметки;
		}
		set {
			if ((value != this._заметки)) {
				this.OnPropertyChanging("Заметки", this._заметки);
				this._заметки = value;
				this.OnPropertyChanged("Заметки");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="SelectedFlag", Storage="_флажокВыбора", ReadOnly=true, FieldType="Computed")]
	public virtual string ФлажокВыбора {
		get {
			return this._флажокВыбора;
		}
		set {
			if ((value != this._флажокВыбора)) {
				this.OnPropertyChanging("ФлажокВыбора", this._флажокВыбора);
				this._флажокВыбора = value;
				this.OnPropertyChanged("ФлажокВыбора");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="NameOrTitle", Storage="_имя0", ReadOnly=true, FieldType="Computed")]
	public virtual string Имя0 {
		get {
			return this._имя0;
		}
		set {
			if ((value != this._имя0)) {
				this.OnPropertyChanging("Имя0", this._имя0);
				this._имя0 = value;
				this.OnPropertyChanged("Имя0");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="RequiredField", Storage="_обязательноеПоле", ReadOnly=true, FieldType="Computed")]
	public virtual string ОбязательноеПоле {
		get {
			return this._обязательноеПоле;
		}
		set {
			if ((value != this._обязательноеПоле)) {
				this.OnPropertyChanging("ОбязательноеПоле", this._обязательноеПоле);
				this._обязательноеПоле = value;
				this.OnPropertyChanged("ОбязательноеПоле");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Keywords", Storage="_ключевыеСлова", FieldType="Note")]
	public virtual string КлючевыеСлова {
		get {
			return this._ключевыеСлова;
		}
		set {
			if ((value != this._ключевыеСлова)) {
				this.OnPropertyChanging("КлючевыеСлова", this._ключевыеСлова);
				this._ключевыеСлова = value;
				this.OnPropertyChanged("КлючевыеСлова");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Thumbnail", Storage="_эскиз", ReadOnly=true, FieldType="Computed")]
	public virtual string Эскиз {
		get {
			return this._эскиз;
		}
		set {
			if ((value != this._эскиз)) {
				this.OnPropertyChanging("Эскиз", this._эскиз);
				this._эскиз = value;
				this.OnPropertyChanged("Эскиз");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Preview", Storage="_вебПросмотр", ReadOnly=true, FieldType="Computed")]
	public virtual string ВебПросмотр {
		get {
			return this._вебПросмотр;
		}
		set {
			if ((value != this._вебПросмотр)) {
				this.OnPropertyChanging("ВебПросмотр", this._вебПросмотр);
				this._вебПросмотр = value;
				this.OnPropertyChanged("ВебПросмотр");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AlternateThumbnailUrl", Storage="_uRLАдресИзображенияДляПросмотра", FieldType="Url")]
	public virtual string URLАдресИзображенияДляПросмотра {
		get {
			return this._uRLАдресИзображенияДляПросмотра;
		}
		set {
			if ((value != this._uRLАдресИзображенияДляПросмотра)) {
				this.OnPropertyChanging("URLАдресИзображенияДляПросмотра", this._uRLАдресИзображенияДляПросмотра);
				this._uRLАдресИзображенияДляПросмотра = value;
				this.OnPropertyChanged("URLАдресИзображенияДляПросмотра");
			}
		}
	}
}

/// <summary>
/// Группировка и описание связанных задач, которое должен выполнить пользователь или рабочая группа.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Суммарная задача", Id="0x012004")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(TtСуммарнаяЗадача))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(ЗадачиСуммарнаяЗадача))]
public partial class СуммарнаяЗадача : Папка {
	
	private System.Nullable<double> _завершения;
	
	private string _основнойТекст;
	
	private System.Nullable<System.DateTime> _датаНачала;
	
	protected System.Nullable<System.DateTime> _срок;
	
	private System.Nullable<Важность> _важность;
	
	protected System.Nullable<СостояниеЗадачи> _состояниеЗадачи;
	
	private System.Nullable<int> _комуНазначеноId;
	
	private string _комуНазначено;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public СуммарнаяЗадача() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PercentComplete", Storage="_завершения", FieldType="Number")]
	public System.Nullable<double> Завершения {
		get {
			return this._завершения;
		}
		set {
			if ((value != this._завершения)) {
				this.OnPropertyChanging("Завершения", this._завершения);
				this._завершения = value;
				this.OnPropertyChanged("Завершения");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Body", Storage="_основнойТекст", FieldType="Note")]
	public string ОсновнойТекст {
		get {
			return this._основнойТекст;
		}
		set {
			if ((value != this._основнойТекст)) {
				this.OnPropertyChanging("ОсновнойТекст", this._основнойТекст);
				this._основнойТекст = value;
				this.OnPropertyChanged("ОсновнойТекст");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="StartDate", Storage="_датаНачала", FieldType="DateTime")]
	public System.Nullable<System.DateTime> ДатаНачала {
		get {
			return this._датаНачала;
		}
		set {
			if ((value != this._датаНачала)) {
				this.OnPropertyChanging("ДатаНачала", this._датаНачала);
				this._датаНачала = value;
				this.OnPropertyChanged("ДатаНачала");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="TaskDueDate", Storage="_срок", FieldType="DateTime")]
	public virtual System.Nullable<System.DateTime> Срок {
		get {
			return this._срок;
		}
		set {
			if ((value != this._срок)) {
				this.OnPropertyChanging("Срок", this._срок);
				this._срок = value;
				this.OnPropertyChanged("Срок");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Priority", Storage="_важность", FieldType="Choice")]
	public System.Nullable<Важность> Важность {
		get {
			return this._важность;
		}
		set {
			if ((value != this._важность)) {
				this.OnPropertyChanging("Важность", this._важность);
				this._важность = value;
				this.OnPropertyChanged("Важность");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="TaskStatus", Storage="_состояниеЗадачи", FieldType="Choice")]
	public virtual System.Nullable<СостояниеЗадачи> СостояниеЗадачи {
		get {
			return this._состояниеЗадачи;
		}
		set {
			if ((value != this._состояниеЗадачи)) {
				this.OnPropertyChanging("СостояниеЗадачи", this._состояниеЗадачи);
				this._состояниеЗадачи = value;
				this.OnPropertyChanged("СостояниеЗадачи");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AssignedTo", Storage="_комуНазначеноId", FieldType="User", IsLookupId=true)]
	public System.Nullable<int> КомуНазначеноId {
		get {
			return this._комуНазначеноId;
		}
		set {
			if ((value != this._комуНазначеноId)) {
				this.OnPropertyChanging("КомуНазначеноId", this._комуНазначеноId);
				this._комуНазначеноId = value;
				this.OnPropertyChanged("КомуНазначеноId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AssignedTo", Storage="_комуНазначено", ReadOnly=true, FieldType="User", IsLookupValue=true)]
	public string КомуНазначено {
		get {
			return this._комуНазначено;
		}
		set {
			if ((value != this._комуНазначено)) {
				this.OnPropertyChanging("КомуНазначено", this._комуНазначено);
				this._комуНазначено = value;
				this.OnPropertyChanged("КомуНазначено");
			}
		}
	}
}

/// <summary>
/// Создание раздела обсуждения.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Обсуждение", Id="0x012002")]
public partial class Обсуждение : Папка {
	
	private string _темаОбсуждения;
	
	private string _версия;
	
	private string _основнойТекст;
	
	private string _ответ;
	
	private string _запись;
	
	private string _цепочкиОбсуждения;
	
	private string _кемРазмещено;
	
	private System.Nullable<System.DateTime> _обновлено;
	
	private string _отправительСообщения;
	
	private System.Nullable<int> _кемИзмененоId;
	
	private string _кемИзмененоNameWithPicture;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Обсуждение() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Title", Storage="_название", Required=true, FieldType="Text")]
	public override string Название {
		get {
			return this._название;
		}
		set {
			if ((value != this._название)) {
				this.OnPropertyChanging("Название", this._название);
				this._название = value;
				this.OnPropertyChanged("Название");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DiscussionTitle", Storage="_темаОбсуждения", ReadOnly=true, FieldType="Computed")]
	public string ТемаОбсуждения {
		get {
			return this._темаОбсуждения;
		}
		set {
			if ((value != this._темаОбсуждения)) {
				this.OnPropertyChanging("ТемаОбсуждения", this._темаОбсуждения);
				this._темаОбсуждения = value;
				this.OnPropertyChanged("ТемаОбсуждения");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_UIVersionString", Storage="_версия", ReadOnly=true, FieldType="Text")]
	public string Версия {
		get {
			return this._версия;
		}
		set {
			if ((value != this._версия)) {
				this.OnPropertyChanging("Версия", this._версия);
				this._версия = value;
				this.OnPropertyChanged("Версия");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Body", Storage="_основнойТекст", FieldType="Note")]
	public string ОсновнойТекст {
		get {
			return this._основнойТекст;
		}
		set {
			if ((value != this._основнойТекст)) {
				this.OnPropertyChanging("ОсновнойТекст", this._основнойТекст);
				this._основнойТекст = value;
				this.OnPropertyChanged("ОсновнойТекст");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ReplyNoGif", Storage="_ответ", ReadOnly=true, FieldType="Computed")]
	public string Ответ {
		get {
			return this._ответ;
		}
		set {
			if ((value != this._ответ)) {
				this.OnPropertyChanging("Ответ", this._ответ);
				this._ответ = value;
				this.OnPropertyChanged("Ответ");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="BodyAndMore", Storage="_запись", ReadOnly=true, FieldType="Computed")]
	public string Запись {
		get {
			return this._запись;
		}
		set {
			if ((value != this._запись)) {
				this.OnPropertyChanging("Запись", this._запись);
				this._запись = value;
				this.OnPropertyChanged("Запись");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Threading", Storage="_цепочкиОбсуждения", ReadOnly=true, FieldType="Computed")]
	public string ЦепочкиОбсуждения {
		get {
			return this._цепочкиОбсуждения;
		}
		set {
			if ((value != this._цепочкиОбсуждения)) {
				this.OnPropertyChanging("ЦепочкиОбсуждения", this._цепочкиОбсуждения);
				this._цепочкиОбсуждения = value;
				this.OnPropertyChanged("ЦепочкиОбсуждения");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PersonViewMinimal", Storage="_кемРазмещено", ReadOnly=true, FieldType="Computed")]
	public string КемРазмещено {
		get {
			return this._кемРазмещено;
		}
		set {
			if ((value != this._кемРазмещено)) {
				this.OnPropertyChanging("КемРазмещено", this._кемРазмещено);
				this._кемРазмещено = value;
				this.OnPropertyChanged("КемРазмещено");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DiscussionLastUpdated", Storage="_обновлено", ReadOnly=true, FieldType="DateTime")]
	public System.Nullable<System.DateTime> Обновлено {
		get {
			return this._обновлено;
		}
		set {
			if ((value != this._обновлено)) {
				this.OnPropertyChanging("Обновлено", this._обновлено);
				this._обновлено = value;
				this.OnPropertyChanged("Обновлено");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EmailSender", Storage="_отправительСообщения", FieldType="Note")]
	public string ОтправительСообщения {
		get {
			return this._отправительСообщения;
		}
		set {
			if ((value != this._отправительСообщения)) {
				this.OnPropertyChanging("ОтправительСообщения", this._отправительСообщения);
				this._отправительСообщения = value;
				this.OnPropertyChanged("ОтправительСообщения");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Имя {
		get {
			throw new System.InvalidOperationException("Field FileLeafRef was removed from content type Обсуждение.");
		}
		set {
			throw new System.InvalidOperationException("Field FileLeafRef was removed from content type Обсуждение.");
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MyEditor", Storage="_кемИзмененоId", ReadOnly=true, FieldType="User", IsLookupId=true)]
	public System.Nullable<int> КемИзмененоId {
		get {
			return this._кемИзмененоId;
		}
		set {
			if ((value != this._кемИзмененоId)) {
				this.OnPropertyChanging("КемИзмененоId", this._кемИзмененоId);
				this._кемИзмененоId = value;
				this.OnPropertyChanged("КемИзмененоId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MyEditor", Storage="_кемИзмененоNameWithPicture", ReadOnly=true, FieldType="User", IsLookupValue=true)]
	public string КемИзмененоNameWithPicture {
		get {
			return this._кемИзмененоNameWithPicture;
		}
		set {
			if ((value != this._кемИзмененоNameWithPicture)) {
				this.OnPropertyChanging("КемИзмененоNameWithPicture", this._кемИзмененоNameWithPicture);
				this._кемИзмененоNameWithPicture = value;
				this.OnPropertyChanged("КемИзмененоNameWithPicture");
			}
		}
	}
}

/// <summary>
/// Создание документа.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Документ", Id="0x0101", List="HR Library")]
public partial class HRLibraryДокумент : Документ {
	
	private System.Nullable<int> _documentApproval;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public HRLibraryДокумент() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Document", Storage="_documentApproval", ReadOnly=true, FieldType="WorkflowStatus")]
	public System.Nullable<int> DocumentApproval {
		get {
			return this._documentApproval;
		}
		set {
			if ((value != this._documentApproval)) {
				this.OnPropertyChanging("DocumentApproval", this._documentApproval);
				this._documentApproval = value;
				this.OnPropertyChanged("DocumentApproval");
			}
		}
	}
}

/// <summary>
/// Отслеживание поручения, которое должен выполнить пользователь или рабочая группа.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Задача", Id="0x0108", List="tt")]
public partial class TtЗадача : Задача {
	
	private Microsoft.SharePoint.Linq.EntitySet<Элемент> _предшественники;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public TtЗадача() {
		this._предшественники = new Microsoft.SharePoint.Linq.EntitySet<Элемент>();
		this._предшественники.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Элемент>>(this.OnПредшественникиSync);
		this._предшественники.OnChanged += new System.EventHandler(this.OnПредшественникиChanged);
		this._предшественники.OnChanging += new System.EventHandler(this.OnПредшественникиChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DueDate", Storage="_срок", FieldType="DateTime")]
	public override System.Nullable<System.DateTime> Срок {
		get {
			return this._срок;
		}
		set {
			if ((value != this._срок)) {
				this.OnPropertyChanging("Срок", this._срок);
				this._срок = value;
				this.OnPropertyChanged("Срок");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Status", Storage="_состояниеЗадачи", FieldType="Choice")]
	public override System.Nullable<СостояниеЗадачи> СостояниеЗадачи {
		get {
			return this._состояниеЗадачи;
		}
		set {
			if ((value != this._состояниеЗадачи)) {
				this.OnPropertyChanging("СостояниеЗадачи", this._состояниеЗадачи);
				this._состояниеЗадачи = value;
				this.OnPropertyChanged("СостояниеЗадачи");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Predecessors", Storage="_предшественники", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Multi, List="tt")]
	public Microsoft.SharePoint.Linq.EntitySet<Элемент> Предшественники {
		get {
			return this._предшественники;
		}
		set {
			this._предшественники.Assign(value);
		}
	}
	
	private void OnПредшественникиChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Предшественники", this._предшественники.Clone());
	}
	
	private void OnПредшественникиChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Предшественники");
	}
	
	private void OnПредшественникиSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Элемент> e) {
	}
}

/// <summary>
/// Отслеживание поручения, которое должен выполнить пользователь или рабочая группа.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Задача", Id="0x0108", List="Задачи")]
public partial class ЗадачиЗадача : Задача {
	
	private Microsoft.SharePoint.Linq.EntitySet<Элемент> _предшественники;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public ЗадачиЗадача() {
		this._предшественники = new Microsoft.SharePoint.Linq.EntitySet<Элемент>();
		this._предшественники.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Элемент>>(this.OnПредшественникиSync);
		this._предшественники.OnChanged += new System.EventHandler(this.OnПредшественникиChanged);
		this._предшественники.OnChanging += new System.EventHandler(this.OnПредшественникиChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DueDate", Storage="_срок", FieldType="DateTime")]
	public override System.Nullable<System.DateTime> Срок {
		get {
			return this._срок;
		}
		set {
			if ((value != this._срок)) {
				this.OnPropertyChanging("Срок", this._срок);
				this._срок = value;
				this.OnPropertyChanged("Срок");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Status", Storage="_состояниеЗадачи", FieldType="Choice")]
	public override System.Nullable<СостояниеЗадачи> СостояниеЗадачи {
		get {
			return this._состояниеЗадачи;
		}
		set {
			if ((value != this._состояниеЗадачи)) {
				this.OnPropertyChanging("СостояниеЗадачи", this._состояниеЗадачи);
				this._состояниеЗадачи = value;
				this.OnPropertyChanged("СостояниеЗадачи");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Predecessors", Storage="_предшественники", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Multi, List="Задачи")]
	public Microsoft.SharePoint.Linq.EntitySet<Элемент> Предшественники {
		get {
			return this._предшественники;
		}
		set {
			this._предшественники.Assign(value);
		}
	}
	
	private void OnПредшественникиChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Предшественники", this._предшественники.Clone());
	}
	
	private void OnПредшественникиChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Предшественники");
	}
	
	private void OnПредшественникиSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Элемент> e) {
	}
}

/// <summary>
/// Создание собрания, крайнего срока или другого события.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Событие", Id="0x0102", List="Календарь")]
public partial class КалендарьСобытие : Событие {
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public КалендарьСобытие() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EventDate", Storage="_времяНачала", Required=true, FieldType="DateTime")]
	public override System.Nullable<System.DateTime> ВремяНачала {
		get {
			return this._времяНачала;
		}
		set {
			if ((value != this._времяНачала)) {
				this.OnPropertyChanging("ВремяНачала", this._времяНачала);
				this._времяНачала = value;
				this.OnPropertyChanged("ВремяНачала");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Description", Storage="_описание", FieldType="Note")]
	public override string Описание {
		get {
			return this._описание;
		}
		set {
			if ((value != this._описание)) {
				this.OnPropertyChanging("Описание", this._описание);
				this._описание = value;
				this.OnPropertyChanged("Описание");
			}
		}
	}
}

/// <summary>
/// Создание вики-страницы.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Вики-страница", Id="0x010108", List="Dev Library")]
public partial class DevLibraryВикиСтраница : ВикиСтраница {
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public DevLibraryВикиСтраница() {
		this.OnCreated();
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string ВикиКонтент {
		get {
			throw new System.InvalidOperationException("Field WikiField was removed from content type Вики-страница.");
		}
		set {
			throw new System.InvalidOperationException("Field WikiField was removed from content type Вики-страница.");
		}
	}
}

/// <summary>
/// Отправка изображения или фотографии.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Рисунок", Id="0x010102", List="Dev Library")]
public partial class DevLibraryРисунок : Рисунок {
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public DevLibraryРисунок() {
		this.OnCreated();
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Образец {
		get {
			throw new System.InvalidOperationException("Field PreviewOnForm was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field PreviewOnForm was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string ТипФайла {
		get {
			throw new System.InvalidOperationException("Field FileType was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field FileType was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string РазмерРисунка {
		get {
			throw new System.InvalidOperationException("Field ImageSize was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field ImageSize was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override System.Nullable<int> ШиринаРисунка {
		get {
			throw new System.InvalidOperationException("Field ImageWidth was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field ImageWidth was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override System.Nullable<int> ВысотаРисунка {
		get {
			throw new System.InvalidOperationException("Field ImageHeight was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field ImageHeight was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override System.Nullable<System.DateTime> ДатаСозданияРисунка {
		get {
			throw new System.InvalidOperationException("Field ImageCreateDate was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field ImageCreateDate was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Заметки {
		get {
			throw new System.InvalidOperationException("Field Comments was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field Comments was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string ФлажокВыбора {
		get {
			throw new System.InvalidOperationException("Field SelectedFlag was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field SelectedFlag was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Имя0 {
		get {
			throw new System.InvalidOperationException("Field NameOrTitle was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field NameOrTitle was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string ОбязательноеПоле {
		get {
			throw new System.InvalidOperationException("Field RequiredField was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field RequiredField was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string КлючевыеСлова {
		get {
			throw new System.InvalidOperationException("Field Keywords was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field Keywords was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Эскиз {
		get {
			throw new System.InvalidOperationException("Field Thumbnail was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field Thumbnail was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string ВебПросмотр {
		get {
			throw new System.InvalidOperationException("Field Preview was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field Preview was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string URLАдресИзображенияДляПросмотра {
		get {
			throw new System.InvalidOperationException("Field AlternateThumbnailUrl was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field AlternateThumbnailUrl was removed from content type Рисунок.");
		}
	}
}

/// <summary>
/// Создание вики-страницы.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Вики-страница", Id="0x010108", List="HR Library")]
public partial class HRLibraryВикиСтраница : ВикиСтраница {
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public HRLibraryВикиСтраница() {
		this.OnCreated();
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string ВикиКонтент {
		get {
			throw new System.InvalidOperationException("Field WikiField was removed from content type Вики-страница.");
		}
		set {
			throw new System.InvalidOperationException("Field WikiField was removed from content type Вики-страница.");
		}
	}
}

/// <summary>
/// Создание вики-страницы.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Вики-страница", Id="0x010108", List="QA Library")]
public partial class QALibraryВикиСтраница : ВикиСтраница {
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public QALibraryВикиСтраница() {
		this.OnCreated();
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string ВикиКонтент {
		get {
			throw new System.InvalidOperationException("Field WikiField was removed from content type Вики-страница.");
		}
		set {
			throw new System.InvalidOperationException("Field WikiField was removed from content type Вики-страница.");
		}
	}
}

/// <summary>
/// Отправка изображения или фотографии.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Рисунок", Id="0x010102", List="QA Library")]
public partial class QALibraryРисунок : Рисунок {
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public QALibraryРисунок() {
		this.OnCreated();
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Образец {
		get {
			throw new System.InvalidOperationException("Field PreviewOnForm was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field PreviewOnForm was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string ТипФайла {
		get {
			throw new System.InvalidOperationException("Field FileType was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field FileType was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string РазмерРисунка {
		get {
			throw new System.InvalidOperationException("Field ImageSize was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field ImageSize was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override System.Nullable<int> ШиринаРисунка {
		get {
			throw new System.InvalidOperationException("Field ImageWidth was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field ImageWidth was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override System.Nullable<int> ВысотаРисунка {
		get {
			throw new System.InvalidOperationException("Field ImageHeight was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field ImageHeight was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override System.Nullable<System.DateTime> ДатаСозданияРисунка {
		get {
			throw new System.InvalidOperationException("Field ImageCreateDate was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field ImageCreateDate was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Заметки {
		get {
			throw new System.InvalidOperationException("Field Comments was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field Comments was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string ФлажокВыбора {
		get {
			throw new System.InvalidOperationException("Field SelectedFlag was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field SelectedFlag was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Имя0 {
		get {
			throw new System.InvalidOperationException("Field NameOrTitle was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field NameOrTitle was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string ОбязательноеПоле {
		get {
			throw new System.InvalidOperationException("Field RequiredField was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field RequiredField was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string КлючевыеСлова {
		get {
			throw new System.InvalidOperationException("Field Keywords was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field Keywords was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Эскиз {
		get {
			throw new System.InvalidOperationException("Field Thumbnail was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field Thumbnail was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string ВебПросмотр {
		get {
			throw new System.InvalidOperationException("Field Preview was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field Preview was removed from content type Рисунок.");
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string URLАдресИзображенияДляПросмотра {
		get {
			throw new System.InvalidOperationException("Field AlternateThumbnailUrl was removed from content type Рисунок.");
		}
		set {
			throw new System.InvalidOperationException("Field AlternateThumbnailUrl was removed from content type Рисунок.");
		}
	}
}

/// <summary>
/// Группировка и описание связанных задач, которое должен выполнить пользователь или рабочая группа.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Суммарная задача", Id="0x012004", List="tt")]
public partial class TtСуммарнаяЗадача : СуммарнаяЗадача {
	
	private Microsoft.SharePoint.Linq.EntitySet<Элемент> _предшественники;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public TtСуммарнаяЗадача() {
		this._предшественники = new Microsoft.SharePoint.Linq.EntitySet<Элемент>();
		this._предшественники.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Элемент>>(this.OnПредшественникиSync);
		this._предшественники.OnChanged += new System.EventHandler(this.OnПредшественникиChanged);
		this._предшественники.OnChanging += new System.EventHandler(this.OnПредшественникиChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DueDate", Storage="_срок", FieldType="DateTime")]
	public override System.Nullable<System.DateTime> Срок {
		get {
			return this._срок;
		}
		set {
			if ((value != this._срок)) {
				this.OnPropertyChanging("Срок", this._срок);
				this._срок = value;
				this.OnPropertyChanged("Срок");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Status", Storage="_состояниеЗадачи", FieldType="Choice")]
	public override System.Nullable<СостояниеЗадачи> СостояниеЗадачи {
		get {
			return this._состояниеЗадачи;
		}
		set {
			if ((value != this._состояниеЗадачи)) {
				this.OnPropertyChanging("СостояниеЗадачи", this._состояниеЗадачи);
				this._состояниеЗадачи = value;
				this.OnPropertyChanged("СостояниеЗадачи");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Predecessors", Storage="_предшественники", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Multi, List="tt")]
	public Microsoft.SharePoint.Linq.EntitySet<Элемент> Предшественники {
		get {
			return this._предшественники;
		}
		set {
			this._предшественники.Assign(value);
		}
	}
	
	private void OnПредшественникиChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Предшественники", this._предшественники.Clone());
	}
	
	private void OnПредшественникиChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Предшественники");
	}
	
	private void OnПредшественникиSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Элемент> e) {
	}
}

/// <summary>
/// Группировка и описание связанных задач, которое должен выполнить пользователь или рабочая группа.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Суммарная задача", Id="0x012004", List="Задачи")]
public partial class ЗадачиСуммарнаяЗадача : СуммарнаяЗадача {
	
	private Microsoft.SharePoint.Linq.EntitySet<Элемент> _предшественники;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public ЗадачиСуммарнаяЗадача() {
		this._предшественники = new Microsoft.SharePoint.Linq.EntitySet<Элемент>();
		this._предшественники.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Элемент>>(this.OnПредшественникиSync);
		this._предшественники.OnChanged += new System.EventHandler(this.OnПредшественникиChanged);
		this._предшественники.OnChanging += new System.EventHandler(this.OnПредшественникиChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DueDate", Storage="_срок", FieldType="DateTime")]
	public override System.Nullable<System.DateTime> Срок {
		get {
			return this._срок;
		}
		set {
			if ((value != this._срок)) {
				this.OnPropertyChanging("Срок", this._срок);
				this._срок = value;
				this.OnPropertyChanged("Срок");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Status", Storage="_состояниеЗадачи", FieldType="Choice")]
	public override System.Nullable<СостояниеЗадачи> СостояниеЗадачи {
		get {
			return this._состояниеЗадачи;
		}
		set {
			if ((value != this._состояниеЗадачи)) {
				this.OnPropertyChanging("СостояниеЗадачи", this._состояниеЗадачи);
				this._состояниеЗадачи = value;
				this.OnPropertyChanged("СостояниеЗадачи");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Predecessors", Storage="_предшественники", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Multi, List="Задачи")]
	public Microsoft.SharePoint.Linq.EntitySet<Элемент> Предшественники {
		get {
			return this._предшественники;
		}
		set {
			this._предшественники.Assign(value);
		}
	}
	
	private void OnПредшественникиChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Предшественники", this._предшественники.Clone());
	}
	
	private void OnПредшественникиChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Предшественники");
	}
	
	private void OnПредшественникиSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Элемент> e) {
	}
}

public enum Важность : int {
	
	None = 0,
	
	Invalid = 1,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(1) Высокая")]
	_1Высокая = 2,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(2) Обычная")]
	_2Обычная = 4,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(3) Низкая")]
	_3Низкая = 8,
}

public enum СостояниеЗадачи : int {
	
	None = 0,
	
	Invalid = 1,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Не начата")]
	НеНачата = 2,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="В процессе выполнения")]
	ВПроцессеВыполнения = 4,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Завершенные")]
	Завершенные = 8,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Отложенные")]
	Отложенные = 16,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Ожидание другого пользователя")]
	ОжиданиеДругогоПользователя = 32,
}

public enum Категория : int {
	
	None = 0,
	
	Invalid = 1,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(1) Категория1")]
	_1Категория1 = 2,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(2) Категория2")]
	_2Категория2 = 4,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(3) Категория3")]
	_3Категория3 = 8,
}
